routes/admin.php
<?php
/*
 * 'middleware' => 'role:admin',
 * 'prefix' => 'admin', 
 * 'namespace' => 'Admin',
 */

use \App\Http\Controllers\Admin\CrmController;
use Illuminate\Support\Facades\Route;

Route::bind('product', function ($id) {
	if (in_array('admin', Route::current()->middleware())) {
		return App\Product::withTrashed()->findOrFail($id);
	} else {
		return App\Product::findOrFail($id);
	}
});

Route::bind('category', function ($id) {
    if (in_array('admin', Route::current()->middleware())) {
        return App\Category::withTrashed()->findOrFail($id);
    } else {
        return App\Category::findOrFail($id);
    }
});

Route::get('/', function() { return view('admin.index'); })->name('dashboard');
Route::get('notifications', 'NotificationController@index')->name('notifications.index');
Route::resource('pages', 'PageController');

/* Users */

Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::post('{user}/auth', 'UserController@auth')->name('auth');
    Route::post('{user}/access', 'UserController@setCategoriesAccess')->name('access');
    Route::resource('invites', 'InviteController');
    Route::post('invites/{invite}/send', 'InviteController@send')->name('invites.send');
    Route::resource('{user}/transactions', 'TransactionController');
});
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

/* Categories */

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('{category}/up', 'CategoryController@up')->name('up');
    Route::get('{category}/down', 'CategoryController@down')->name('down');
    Route::put('{category}/recovery', 'CategoryController@recovery')->name('recovery');
    Route::get('{category}/exportToWord', 'ExportController@toWord')->name('toWord');
    Route::get('{category}/exportToCsv', 'ExportController@categoryToCsv')->name('toCsv');
});
Route::resource('categories', 'CategoryController');

/* Products*/

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('search', 'ProductController@search')->name('search');
    Route::get('create/{product}', 'ProductController@create')->name('createAs');
    Route::get('{product}/sort', 'ProductController@sorting')->name('sorting');
    Route::post('move', 'ProductController@moving')->name('moving');
    Route::post('to-category', 'ProductController@moving')->name('toCategory');
    Route::post('add-supplier', 'ProductController@addSupplier')->name('addSupplier');
    Route::post('exportToWord', 'ExportController@productsToWord')->name('toWord');
    Route::post('exportToBlock', 'ExportController@productsToBlock')->name('toBlock');
    Route::post('exportToCsv', 'ExportController@productsToCsv')->name('toCsv');
    Route::post('sortToTop', 'ProductController@sortToTop')->name('toTop');
    Route::post('{product}/restore', 'ProductController@restore')->name('restore');

    Route::post('parsers/{parser}', 'ParserProductController@parse')->name('parsers.parse');
    Route::resource('parsers', 'ParserProductController')->only(['index', 'edit', 'update']);
});
Route::resource('products', 'ProductController');
Route::resource('brands', 'BrandController');

/* Orders */

Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
    Route::get('{order}/blank', 'OrderController@toOrderForm')->name('blank');
    Route::get('{order}/csv', 'OrderController@toCsv')->name('toCsv');
    Route::get('{order}/doc', 'OrderController@toWord')->name('toWord');
    Route::get('{order}/crm', 'CrmController@invoice')->name('toCrm');
});
Route::resource('orders', 'OrderController');
Route::resource('carts', 'CartController');
Route::resource('suppliers', 'SupplierController');

Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
    Route::get('uploads', 'ImageController@uploads')->name('uploads');
    Route::post('uploads', 'ImageController@stores')->name('stores');
});
Route::resource('images', 'ImageController');

/* Utils */

Route::prefix('import')->group(function () {
    Route::get('/', 'ImportController@index')->name('import.index');
    Route::post('/', 'ImportController@parse')->name('import.parse');
    Route::post('/{import}/check', 'ImportController@check')->name('import.check');
    Route::get('/{import}/check', 'ImportController@checked')->name('import.checked'); 
    Route::get('/finish', 'ImportController@finish')->name('import.finish'); 
    Route::get('/{import}', 'ImportController@show')->name('imports.show');
    Route::post('/{import}', 'ImportController@store')->name('import.store'); 
});

Route::post('/parsers/mass', 'ParserController@massStore')->name('parsers.store.mass');
Route::resource('parsers', 'ParserController')
    ->only('index', 'store', 'show');

Route::group(['prefix' => 'mailings', 'as' => 'mailings.'], function () {
    Route::post('/preview', 'MailingController@preview')->name('preview');
    Route::get('/{mailing}/prepare', 'MailingController@prepare')->name('prepare');
    Route::post('/{mailing}/send', 'MailingController@send')->name('send');
});
Route::resource('mailings', 'MailingController');

Route::get('helper/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('helpers.logs');
Route::post('helper/combine', 'HelperController@combine')->name('helpers.combine');
Route::post('helper/word', 'HelperController@fromWord')->name('helpers.fromWord');
Route::get('helper', 'HelperController@index')->name('helpers.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'CategoryController@index')->name('catalog');
Route::get('category/{category}', 'CategoryController@show')->name('catalog.show');
Route::get('product/{product}', 'ProductController@show')->name('products.show');
Route::get('search', 'ProductController@search')->name('products.search');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/', 'HomeController@dashboard')->name('dashboard');
        Route::get('notifications', 'HomeController@notifications')->name('notifications.index');
        Route::get('orders', 'OrderController@index')->name('orders.index');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
    });
});


Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('add-to-cart', 'CartController@addToCart')->name('add-to-cart');
    Route::get('add/{offer}', 'CartController@add')->name('add');
    Route::get('remove/{offer}', 'CartController@remove')->name('remove');
    Route::get('delete/{offer}', 'CartController@removeAll')->name('delete');
    Route::get('clear', 'CartController@clearCart')->name('clear');
    Route::post('order', 'CartController@saveOrder')->name('order');
});

Route::any('test', 'HomeController@test');

Route::redirect('home', '/')->name('home');
Route::view('about', 'pages.about')->name('about');
Route::view('rules', 'pages.rules')->name('rules');
Route::view('contacts', 'pages.contacts')->name('contacts');
Route::view('feedback', 'pages.feedback')->name('feedback');

Route::get('catalog/{path?}', function($path = '/') {
    return redirect($path);
})->where('path', '.*');;

Route::get('{page}', 'PageController@show')->name('pages.show');

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Image extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'hash', 'url',
    ];

    public function products()
    {
        return $this
            ->belongsToMany(Product::class)
            ->withTrashed();
    }

    public function upload()
    {
        return $this
            ->hasMany(UploadImage::class);
    }

    public function getUploadDir()
    {
        return substr($this->hash, 0, 2) . '/' . substr($this->hash, 2, 2);
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ImageController extends Controller
{
    /**
     * undocumented class variable
     *
     * @var string
     **/
    private $indexView = 'admin.images.index';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::with('products');
        $perPage = request('count') ?? 96;

        if (request('used') == 'false') {
            $images = $images->has('products', 0);
        }

        if (request('table') == 'true') {
            $this->indexView = 'admin.images.table';
        }

        $images = $images->orderBy('id', 'desc')->paginate($perPage);
        return view($this->indexView, compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function show(Image $image)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function edit(Image $image)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Image $image)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function destroy(Image $image)
    {
        $image->delete();
        return back();
    }


    public function uploads(Request $request)
    {
        return view('admin.images.uploads');
    }

    public function stores(Request $request)
    {
        $files = $request->file('images') ?? [$request->file('image')] ?? [];
        $localHost = parse_url(config('app.url'))['host'];
        $disk = 'images';

        $images = array();
        foreach ($files as $file) {
            $hash = sha1_file($file->getRealPath());
            $image = Image::firstOrNew(['hash' => $hash]);
            if ($image->exists) {
                $url = parse_url($image->url);
                if (isset($url['host']) && $url['host'] != $localHost) {
                    $extension = $file->extension();
                    $path = substr($hash, 0, 2) . '/' . substr($hash, 2, 2);
                    $url = $hash . '.' . $extension;
                    $url = $file->storeAs($path, $url, $disk);
                    $image->upload_url = $image->url;
                    $image->url = config('app.url') . '/images/' . $url;
                    $image->save();
                } elseif (!isset($url['host'])) {
                    $image->url = config('app.url') . $image->url;
                    $image->save();
                }
                $image->upload_url = $file->getClientOriginalName();
            } else {
                $extension = $file->extension();
                $path = substr($hash, 0, 2) . '/' . substr($hash, 2, 2);
                $url = $hash . '.' . $extension;
                $url = $file->storeAs($path, $url, $disk);
                $image->url = config('app.url') . '/images/' . $url;
                $image->upload_url = $file->getClientOriginalName();
                $image->save();
            }

            $images[] = $image;
        }

        return view('admin.images.resault', compact('images'));

        /*$disk = Storage::disk('images');

        foreach ($request->file('file-list') as $file) {

            $filename = Filename::first();

            $disk->putFile('', $file);

            Image::create([
                'filename' => $filename->name,
                'title' => $file->getClientOriginalName(),
                'extension' => $file->guessClientExtension(),
                'size' => $file->getClientSize(),
                'mime' => $file->getClientMimeType(),
                'hash' => md5_file($file->getRealPath()),
            ]);

            $filename->delete();
        }*/
    }
}

resources/views/admin/images/index.blade.php
@extends('admin.index')

@section('content')
    <a class="btn btn-sm btn-outline-secondary float-right ml-2" href="{{ route('admin.images.uploads') }}">Массовая загрузка</a>

    <h3>Изображения</h3>
    
    @if ($images->count())
        @include('partials.pagination', ['items' => $images, 'appends' => ['used' => Request::input('used')]])
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}">Все</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}?used=false">Не используемые</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}?table=true">Таблицей</a>
            </li>
        </ul>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Изображение</th>
                        <th>Ссылка</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($images as $image)
                        <tr>
                            <td><img src="{{ $image->url }}" title="Загружено: {{ $image->upload_url }}" style="width: 15rem;" data-tooltip="true"></td>
                            <td>
                                <form class="d-inline form-delete" action="{{ route('admin.images.destroy', $image) }}" method="post">
                                    {{ csrf_field() }} {{ method_field('DELETE') }}
                                    <button class="btn btn-danger" type="submit" data-tooltip="true" title="Удалить">
                                        <i class="material-icons">&#xE872;</i>
                                    </button>
                                </form>
                                <button class="btn btn-light copy-url" data-tooltip="true" title="Копировать в буфер обмена">
                                    <i class="material-icons">&#xE14D;</i>
                                </button> 
                                <span class="image-url">{{ $image->url }}</span> 
                                <hr>
                                @if ($image->products->count())
                                    <p class="h6">Используется в товарах:</p>
                                    @foreach ($image->products as $product)
                                        <a class="btn btn-secondary mr-2" href="{{ route('admin.products.edit', $product) }}">
                                        @if ($product->trashed()) <s> @endif
                                            {{ $product->vendor_code }}
                                        @if ($product->trashed()) </s> @endif
                                        </a>
                                    @endforeach
                                @else
                                    <div class="alert alert-warning">Не используется</div>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['items' => $images])
    @else
        <p>Отсутствуют</p>
    @endif

@endsection

resources/views/admin/images/result.blade.php
@extends('admin.index')

@section('content')

    @if (count($images))
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Изображение</th>
                        <th>Загружаемый файл</th>
                        <th>Ссылка на загруженное изображение</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($images as $image)
                        <tr>
                            <td><img src="{{ $image->url }}" style="width: 5rem;"></td>
                            <td>{{ $image->upload_url }}</td>
                            <td>
                                <button class="btn btn-light copy-url" data-toggle="tooltip" data-placement="bottom" title="Копировать в буфер обмена">
                                    <i class="material-icons">&#xE14D;</i>
                                </button> 
                                <span class="image-url">{{ $image->url }}</span> 
                                @if ($image->products->count())
                                    <hr>
                                    @foreach ($image->products as $product)
                                        <a class="btn btn-secondary mr-2" href="{{ route('admin.products.edit', $product) }}">
                                        @if ($product->trashed()) <s> @endif
                                            {{ $product->vendor_code }}
                                        @if ($product->trashed()) </s> @endif
                                        </a>
                                    @endforeach
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @else
        <p>Загруженные файлы отсутствуют</p>
    @endif

@endsection

@push('scripts')
    <script>
        let copyUrlBtns = document.querySelectorAll('.copy-url');  
        copyUrlBtns.forEach(function(entry) {
            entry.addEventListener('click', function(event) {  
                window.getSelection().removeAllRanges();
                
                let imageLink = this.nextElementSibling;  
                let range = document.createRange();  
                range.selectNode(imageLink);  
                window.getSelection().addRange(range);  

                try {  
                    let successful = document.execCommand('copy');  
                    let msg = successful ? 'successful' : 'unsuccessful';  
                    console.log('Copy url command was ' + msg + ': ' + range);  
                } catch(err) {  
                    console.log('Oops, unable to copy');  
                }  

                window.getSelection().removeAllRanges();  
            });
        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
@endpush

resources/views/admin/images/table.blade.php
@extends('admin.index')

@section('content')
    <a class="btn btn-sm btn-outline-secondary float-right ml-2" href="{{ route('admin.images.uploads') }}">Массовая загрузка</a>

    <h3>Изображения</h3>
    
    @if ($images->count())
        @include('partials.pagination', ['items' => $images, 'appends' => ['used' => Request::input('used'), 'table' => Request::input('table')]])
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}">Все</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}?used=false">Не используемые</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ \URL::current() }}?table=true">Таблицей</a>
            </li>
        </ul>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Исходный файл</th>
                        <th>Ссылка</th>
                        <th>Дата загрузки</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($images as $image)
                        <tr>
                            <td>{{ $image->upload_url }}</td>
                            <td>{{ $image->url }}</td>
                            <td>@datetime($image->created_at)</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['items' => $images])
    @else
        <p>Отсутствуют</p>
    @endif

@endsection

@push('scripts')
    <script>
        let copyUrlBtns = document.querySelectorAll('.copy-url');  
        copyUrlBtns.forEach(function(entry) {
            entry.addEventListener('click', function(event) {  
                window.getSelection().removeAllRanges();
                
                let imageLink = this.nextElementSibling;  
                let range = document.createRange();  
                range.selectNode(imageLink);  
                window.getSelection().addRange(range);  

                try {  
                    let successful = document.execCommand('copy');  
                    let msg = successful ? 'successful' : 'unsuccessful';  
                    console.log('Copy url command was ' + msg + ': ' + range);  
                } catch(err) {  
                    console.log('Oops, unable to copy');  
                }  

                window.getSelection().removeAllRanges();  
            });
        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
@endpush

resources/views/admin/images/uploads.blade.php
@extends('admin.index')

@section('content')
    <h3>Массовая загрузка изображений</h3>

    <form class="form-inline" method="POST" action="{{ route('admin.images.stores') }}" enctype="multipart/form-data" id="upload-form">
        <div class="form-group">
            <label for="images">Выберите изображения:</label>
            <input type="file" class="form-control-file" name="images[]" id="images" accept="image/*" required multiple>
        </div>
        @if ($errors->has('images'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('images') }}</strong>
            </span>
        @endif
        <button type="submit" class="btn btn-primary btn-sm">Загрузить</button>
        {{ csrf_field() }} 
    </form>

    <div class="images-container" id="upload-dropzone">Просто перетащите файлы сюда</div>
    <!-- Progress Bar -->
    <div class="progress" id="upload-progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
            <span></span>
            <span class="sr-only">0% Complete</span>
        </div>
    </div>
    <!-- Upload Finished -->
    <div class="upload-finished list-group" id="upload-previews">
        <p class="upload-finished-title h5">Загружаемые файлы:</p>
    </div>

    <div id="template">
        <div class="d-flex justify-content-between mb-1">
            <!-- This is used as the file preview template -->
            <div>
                <span class="preview"><img data-dz-thumbnail></span>
            </div>
            <div>
                <p class="name" data-dz-name></p>
                <strong class="error text-danger" data-dz-errormessage></strong>
            </div>
            <div>
                <p class="size" data-dz-size></p>
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                    <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
                </div>
            </div>
            <div>
                <button class="btn btn-primary start">
                    <i class="fas fa-upload"></i>
                    <span>Start</span>
                </button>
                <button data-dz-remove class="btn btn-warning cancel">
                    <i class="fas fa-ban"></i>
                    <span>Cancel</span>
                </button>
                <button data-dz-remove class="btn btn-danger delete">
                    <i class="fas fa-trash"></i>
                    <span>Delete</span>
                </button>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/images.manage.js') }}"></script>
@endpush