routes/admin.php
<?php
/*
 * 'middleware' => 'role:admin',
 * 'prefix' => 'admin', 
 * 'namespace' => 'Admin',
 */

use \App\Http\Controllers\Admin\CrmController;
use Illuminate\Support\Facades\Route;

Route::bind('product', function ($id) {
	if (in_array('admin', Route::current()->middleware())) {
		return App\Product::withTrashed()->findOrFail($id);
	} else {
		return App\Product::findOrFail($id);
	}
});

Route::bind('category', function ($id) {
    if (in_array('admin', Route::current()->middleware())) {
        return App\Category::withTrashed()->findOrFail($id);
    } else {
        return App\Category::findOrFail($id);
    }
});

Route::get('/', function() { return view('admin.index'); })->name('dashboard');
Route::get('notifications', 'NotificationController@index')->name('notifications.index');
Route::resource('pages', 'PageController');

/* Users */

Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::post('{user}/auth', 'UserController@auth')->name('auth');
    Route::post('{user}/access', 'UserController@setCategoriesAccess')->name('access');
    Route::resource('invites', 'InviteController');
    Route::post('invites/{invite}/send', 'InviteController@send')->name('invites.send');
    Route::resource('{user}/transactions', 'TransactionController');
});
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

/* Categories */

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('{category}/up', 'CategoryController@up')->name('up');
    Route::get('{category}/down', 'CategoryController@down')->name('down');
    Route::put('{category}/recovery', 'CategoryController@recovery')->name('recovery');
    Route::get('{category}/exportToWord', 'ExportController@toWord')->name('toWord');
    Route::get('{category}/exportToCsv', 'ExportController@categoryToCsv')->name('toCsv');
});
Route::resource('categories', 'CategoryController');

/* Products*/

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('search', 'ProductController@search')->name('search');
    Route::get('create/{product}', 'ProductController@create')->name('createAs');
    Route::get('{product}/sort', 'ProductController@sorting')->name('sorting');
    Route::post('move', 'ProductController@moving')->name('moving');
    Route::post('to-category', 'ProductController@moving')->name('toCategory');
    Route::post('add-supplier', 'ProductController@addSupplier')->name('addSupplier');
    Route::post('exportToWord', 'ExportController@productsToWord')->name('toWord');
    Route::post('exportToBlock', 'ExportController@productsToBlock')->name('toBlock');
    Route::post('exportToCsv', 'ExportController@productsToCsv')->name('toCsv');
    Route::post('sortToTop', 'ProductController@sortToTop')->name('toTop');
    Route::post('{product}/restore', 'ProductController@restore')->name('restore');

    Route::post('parsers/{parser}', 'ParserProductController@parse')->name('parsers.parse');
    Route::resource('parsers', 'ParserProductController')->only(['index', 'edit', 'update']);
});
Route::resource('products', 'ProductController');
Route::resource('brands', 'BrandController');

/* Orders */

Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
    Route::get('{order}/blank', 'OrderController@toOrderForm')->name('blank');
    Route::get('{order}/csv', 'OrderController@toCsv')->name('toCsv');
    Route::get('{order}/doc', 'OrderController@toWord')->name('toWord');
    Route::get('{order}/crm', 'CrmController@invoice')->name('toCrm');
});
Route::resource('orders', 'OrderController');
Route::resource('carts', 'CartController');
Route::resource('suppliers', 'SupplierController');

Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
    Route::get('uploads', 'ImageController@uploads')->name('uploads');
    Route::post('uploads', 'ImageController@stores')->name('stores');
});
Route::resource('images', 'ImageController');

/* Utils */

Route::prefix('import')->group(function () {
    Route::get('/', 'ImportController@index')->name('import.index');
    Route::post('/', 'ImportController@parse')->name('import.parse');
    Route::post('/{import}/check', 'ImportController@check')->name('import.check');
    Route::get('/{import}/check', 'ImportController@checked')->name('import.checked'); 
    Route::get('/finish', 'ImportController@finish')->name('import.finish'); 
    Route::get('/{import}', 'ImportController@show')->name('imports.show');
    Route::post('/{import}', 'ImportController@store')->name('import.store'); 
});

Route::post('/parsers/mass', 'ParserController@massStore')->name('parsers.store.mass');
Route::resource('parsers', 'ParserController')
    ->only('index', 'store', 'show');

Route::group(['prefix' => 'mailings', 'as' => 'mailings.'], function () {
    Route::post('/preview', 'MailingController@preview')->name('preview');
    Route::get('/{mailing}/prepare', 'MailingController@prepare')->name('prepare');
    Route::post('/{mailing}/send', 'MailingController@send')->name('send');
});
Route::resource('mailings', 'MailingController');

Route::get('helper/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('helpers.logs');
Route::post('helper/combine', 'HelperController@combine')->name('helpers.combine');
Route::post('helper/word', 'HelperController@fromWord')->name('helpers.fromWord');
Route::get('helper', 'HelperController@index')->name('helpers.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'CategoryController@index')->name('catalog');
Route::get('category/{category}', 'CategoryController@show')->name('catalog.show');
Route::get('product/{product}', 'ProductController@show')->name('products.show');
Route::get('search', 'ProductController@search')->name('products.search');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/', 'HomeController@dashboard')->name('dashboard');
        Route::get('notifications', 'HomeController@notifications')->name('notifications.index');
        Route::get('orders', 'OrderController@index')->name('orders.index');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
    });
});


Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('add-to-cart', 'CartController@addToCart')->name('add-to-cart');
    Route::get('add/{offer}', 'CartController@add')->name('add');
    Route::get('remove/{offer}', 'CartController@remove')->name('remove');
    Route::get('delete/{offer}', 'CartController@removeAll')->name('delete');
    Route::get('clear', 'CartController@clearCart')->name('clear');
    Route::post('order', 'CartController@saveOrder')->name('order');
});

Route::any('test', 'HomeController@test');

Route::redirect('home', '/')->name('home');
Route::view('about', 'pages.about')->name('about');
Route::view('rules', 'pages.rules')->name('rules');
Route::view('contacts', 'pages.contacts')->name('contacts');
Route::view('feedback', 'pages.feedback')->name('feedback');

Route::get('catalog/{path?}', function($path = '/') {
    return redirect($path);
})->where('path', '.*');;

Route::get('{page}', 'PageController@show')->name('pages.show');

app/Product.php
<?php

namespace App;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
    use Searchable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'vendor_code', 'name', 'description', 'price', 
        'category_id', 'unit_id',
        'sorted_at',
    ];

    /**
     * Атрибуты, которые должны быть преобразованы к базовым типам.
     *
     * @var array
     */
    protected $casts = [
        'price' => 'integer',
        'sorted_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    private $units = [
        1 => 'piece',
        2 => 'set',
        3 => 'pack',
        4 => 'size_range',
    ];

    private $statuses = [
        1 => 'in_stock',
        2 => 'out_of_stock',
        3 => 'pre_order',
    ];

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'creating' => \App\Events\ProductCreating::class,
    ];

    /**
     * Получить категории данного товара.
     */
    public function category()
    {
        return $this->belongsTo(Category::class)->withTrashed();
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * Получить сопутствующие товары.
     */
    public function related()
    {
        return $this->belongsToMany(self::class, 'product_product', 'product_id', 'related_id');
    }
    public function relatedBy()
    {
        return $this->belongsToMany(self::class, 'product_product', 'related_id', 'product_id');
    }

    public function images()
    {
        return $this->belongsToMany(Image::class)
            ->withPivot('status', 'sort', 'description')
            ->oldest('image_product.sort')
            ->oldest('id')
        ;
    }

    public function image()
    {
        return $this->hasOne(ImageProduct::class)
        ;
    }

    public function options()
    {
        return $this->belongsToMany(Option::class, 'offers')
            ->as('offer')
            ->withPivot('id', 'status')
            ->wherePivot('status', 1)
        ;
    }

    public function offers()
    {
        return $this->belongsToMany(Offer::class);
    }

    public function suppliers()
    {
        return $this->belongsToMany(Supplier::class);
    }

    public function mailings()
    {
        return $this->belongsToMany(Mailing::class);
    }

    /**
     * Заготовка запроса доступных товаров.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeAvailable($query)
    {
        return $query->where('available', '!=', 0);
    }
    
    /**
     * @return string
     */
    public function getIsNewAttribute()
    {
        return $this->created_at->diffInDays(now()) <= 7;
    }

    public function getUnitAttribute()
    {
        return $this->units[$this->unit_id];
    }

    public function getAvailabilityAttribute()
    {
        return $this->statuses[$this->status_id];
    }

    /* Product's helpers */
    
    public function getUnits()
    {
        return $this->units;
    }

    public function getStatuses()
    {
        return $this->statuses;
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Product;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function search(Request $request)
    {
        $products = Product::whereRaw('MATCH(vendor_code, name, description) AGAINST(? IN BOOLEAN MODE)', [$request->text])
            ->with('images:url')
            ->select(['id', 'vendor_code as title'])
            ->take(10)
            ->get();

        return response()->json($products->keyBy('id'));
    }

    public function attach(Request $request)
    {
        $relationship = $request->type;
        $relationshipId = $request->type_id;

        $product = Product::find($request->id);
        $product->$relationship()->sync($relationshipId, false);

        return $this->get($request);
    }
    
    public function detach(Request $request)
    {
        $relationship = $request->type;
        $relationshipId = $request->type_id;

        $product = Product::find($request->id);
        $product->$relationship()->detach($relationshipId);

        return $this->get($request);
    }

    public function get(Request $request)
    {
        $relationship = $request->type;
        $relationshipId = $request->type_id;

        $products = Product::with('images:url')->whereHas($relationship, function ($query) use ($relationshipId) {
            $query->where('id', $relationshipId);
        })->get(['id', 'vendor_code as title']);

        return response()->json($products->keyBy('id'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $viewShow = 'products.show';
    protected $viewSearch = 'products.search';

    /**
     * Display the product.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    protected function show(Product $product)
    {
        $product->load(['options' => function ($query) {
                $query->where('status', 1);
            }]);

        $product->load(['images' => function ($query) {
            return $query->orderBy('image_product.sort','ASC');
        }]);
        
        $product->load('related');
        
        return view($this->viewShow, compact('product'));
    }

    /**
     * Display the products by search params.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    protected function search(Request $request)
    {
        /*if (\Auth::check() == false || (\Auth::check() && \Auth::user()->role) == false) {
            abort(403, 'Unauthorized action.');
        }*/
        
        $perPage = (int) $request->count ?: 12;
        /*$categoriesIds = \Auth::user()->role->categories()->pluck('id');*/

        $products = Product::whereRaw(
                'MATCH(vendor_code, name, description) AGAINST(? IN BOOLEAN MODE)',
                [$request->text]
            )
            /*->whereIn('category_id', $categoriesIds)*/
            ->withCount('images', 'options')
            ->with('images')
            ->paginate($perPage);

        return view($this->viewSearch, compact('products'))->withInput($request->all());
    }

}

resources/views/products/search.blade.php
@extends('layouts.default')

@section('content')

    <div class="row">
        <div class="col-lg-3">@include('categories.partials.list', ['parent' => 0])</div>
        <div class="col-lg-9">
            <div class="mb-3">
                @include('partials.search')
            </div>

            @if ($products->count())
                @include('partials.pagination', ['items' => $products])
                <div class="row">
                    @foreach ($products as $product)
                        @include('products.partials.products_card', compact('product'))
                    @endforeach
                </div>
                @include('partials.pagination', ['items' => $products])
            @else
                <div class="card bg-secondary mb-3">
                    <div class="card-body">
                        <p class="text-white text-center m-0">Товары отсутствуют!</p>
                    </div>
                </div>
            @endif

        </div><!-- /col-lg-9 -->
    </div><!-- /.row -->

@endsection

resources/views/products/show.blade.php
@extends('layouts.default')
@section('title', $product->vendor_code)

@section('content')
    <nav class="navigation__block" aria-label="breadcrumb" role="navigation">
        <ul class="navigation-breadcrumb__block">
            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
            <li class="breadcrumb-item"><a href="{{ route('catalog') }}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{ route('catalog.show', $product->category_id) }}">{{$product->category->name}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $product->vendor_code }}</li>
        </ul>
        <div class="navigation-search__block">
            @include('partials.search')
        </div>
    </nav>
    <section id="product" itemscope itemtype="https://schema.org/Product">
        @if ($product->availability == 'pre_order')
            <div class="bar-diagonal__wrapper">
                <div class="bar-diagonal__block">@lang('product.availability.' . $product->availability)</div>
            </div>
        @endif
        @if ($product->is_new)<span class="badge badge-pill badge-danger float-right mt-1 mr-1">Новинка</span>@endif
        <h1 itemprop="name">{{ $product->vendor_code }}</h1>
        <div class="row">
            <div class="col-sm-6">
                <div id="carousel-{{$product->id}}" class="carousel slide" data-ride="carousel" data-interval="2500">
                    <div class="carousel-inner">
                        @foreach ($product->images as $image)
                            <div class="carousel-item @if ($loop->first) active  @endif">
                                <img class="d-block w-100" src="{{ $image->url }}" itemprop="image" alt="{{ $product->name }}">

                                @if ($image->pivot->description)
                                    <div class="carousel-caption d-none d-md-block">
                                    <p>{{ $image->pivot->description }}</p>
                                    </div>
                                @endif
                            </div>
                        @endforeach
                        @if ( $product->images->count() > 1 )
                            <a class="carousel-control-prev" href="#carousel-{{ $product->id }}" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-{{ $product->id }}" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        @endif
                    </div>
                    @if ( $product->images->count() > 1 )
                        <div class="carousel-indicators-static carousel-indicators">
                            @foreach ($product->images as $image)
                                <div data-target="#carousel-{{ $product->id }}" data-slide-to="{{ $loop->iteration - 1 }}" class="carousel-thumbs @if ($loop->first) active @endif ">
                                    <img src="{{ $image->url }}" class="w-100">
                                </div>
                            @endforeach
                        </div>
                    @endif
                </div>
            </div>
            <div class="col-sm-6">
                <p class="card-header">Описание</p>
                <div class="card-body">
                    <p class="card-text" itemprop="description">
                        {{ $product->description }}
                    </p>
                </div>

                @if ($product->options->count())
                    <p class="card-header">Размер, цвет</p>
                    <div class="row" id="product-options">
                        @foreach ($product->options->chunk(ceil($product->options->count()/2)) as $options)
                            <ul class="col-sm-6 my-3">
                                @foreach ($options as $option)
                                    <li class="nav-link position-relative">
                                        @include('products.partials.add_to_cart', ['offer' => $option->offer, 'option' => $option])
                                    </li>
                                @endforeach
                            </ul>
                        @endforeach
                    </div>
                    <div class="card-header">
                        @lang('product.price.per_' . $product->unit)
                    </div>
                    <div class="card-body" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <p class="card-text h5">@money($product->price) руб.</p>
                        <meta itemprop="price" content="{{ intval($product->price * 1.7) }}">
                        <meta itemprop="priceCurrency" content="RUB">
                        <meta itemprop="priceValidUntil" content="{{ date('Y') }}-12-31T23:59:59">
                        <link itemprop="url" href="{{ $product->present()->route }}">
                        <link itemprop="availability" href="http://schema.org/InStock">
                    </div>
                @endif
            </div>
        </div>
        <meta itemprop="productID" content="{{ $product->id }}">
        <meta itemprop="sku" content="{{ $product->present()->sku }}">
    </section>
    @if ($product->related->count())
    <div class="card bg-light mt-5">
        <h5 class="card-header">Вместе с этим товаром покупают</h5>
        <div class="card-body row justify-content-center">
            @foreach ($product->related as $related)
                @include('products.partials.products_card', ['product' => $related])
            @endforeach
        </div>
    </div>
    @endif
@endsection