routes/admin.php
<?php
/*
 * 'middleware' => 'role:admin',
 * 'prefix' => 'admin', 
 * 'namespace' => 'Admin',
 */

use \App\Http\Controllers\Admin\CrmController;
use Illuminate\Support\Facades\Route;

Route::bind('product', function ($id) {
	if (in_array('admin', Route::current()->middleware())) {
		return App\Product::withTrashed()->findOrFail($id);
	} else {
		return App\Product::findOrFail($id);
	}
});

Route::bind('category', function ($id) {
    if (in_array('admin', Route::current()->middleware())) {
        return App\Category::withTrashed()->findOrFail($id);
    } else {
        return App\Category::findOrFail($id);
    }
});

Route::get('/', function() { return view('admin.index'); })->name('dashboard');
Route::get('notifications', 'NotificationController@index')->name('notifications.index');
Route::resource('pages', 'PageController');

/* Users */

Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::post('{user}/auth', 'UserController@auth')->name('auth');
    Route::post('{user}/access', 'UserController@setCategoriesAccess')->name('access');
    Route::resource('invites', 'InviteController');
    Route::post('invites/{invite}/send', 'InviteController@send')->name('invites.send');
    Route::resource('{user}/transactions', 'TransactionController');
});
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

/* Categories */

Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
    Route::get('{category}/up', 'CategoryController@up')->name('up');
    Route::get('{category}/down', 'CategoryController@down')->name('down');
    Route::put('{category}/recovery', 'CategoryController@recovery')->name('recovery');
    Route::get('{category}/exportToWord', 'ExportController@toWord')->name('toWord');
    Route::get('{category}/exportToCsv', 'ExportController@categoryToCsv')->name('toCsv');
});
Route::resource('categories', 'CategoryController');

/* Products*/

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('search', 'ProductController@search')->name('search');
    Route::get('create/{product}', 'ProductController@create')->name('createAs');
    Route::get('{product}/sort', 'ProductController@sorting')->name('sorting');
    Route::post('move', 'ProductController@moving')->name('moving');
    Route::post('to-category', 'ProductController@moving')->name('toCategory');
    Route::post('add-supplier', 'ProductController@addSupplier')->name('addSupplier');
    Route::post('exportToWord', 'ExportController@productsToWord')->name('toWord');
    Route::post('exportToBlock', 'ExportController@productsToBlock')->name('toBlock');
    Route::post('exportToCsv', 'ExportController@productsToCsv')->name('toCsv');
    Route::post('sortToTop', 'ProductController@sortToTop')->name('toTop');
    Route::post('{product}/restore', 'ProductController@restore')->name('restore');

    Route::post('parsers/{parser}', 'ParserProductController@parse')->name('parsers.parse');
    Route::resource('parsers', 'ParserProductController')->only(['index', 'edit', 'update']);
});
Route::resource('products', 'ProductController');
Route::resource('brands', 'BrandController');

/* Orders */

Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
    Route::get('{order}/blank', 'OrderController@toOrderForm')->name('blank');
    Route::get('{order}/csv', 'OrderController@toCsv')->name('toCsv');
    Route::get('{order}/doc', 'OrderController@toWord')->name('toWord');
    Route::get('{order}/crm', 'CrmController@invoice')->name('toCrm');
});
Route::resource('orders', 'OrderController');
Route::resource('carts', 'CartController');
Route::resource('suppliers', 'SupplierController');

Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
    Route::get('uploads', 'ImageController@uploads')->name('uploads');
    Route::post('uploads', 'ImageController@stores')->name('stores');
});
Route::resource('images', 'ImageController');

/* Utils */

Route::prefix('import')->group(function () {
    Route::get('/', 'ImportController@index')->name('import.index');
    Route::post('/', 'ImportController@parse')->name('import.parse');
    Route::post('/{import}/check', 'ImportController@check')->name('import.check');
    Route::get('/{import}/check', 'ImportController@checked')->name('import.checked'); 
    Route::get('/finish', 'ImportController@finish')->name('import.finish'); 
    Route::get('/{import}', 'ImportController@show')->name('imports.show');
    Route::post('/{import}', 'ImportController@store')->name('import.store'); 
});

Route::post('/parsers/mass', 'ParserController@massStore')->name('parsers.store.mass');
Route::resource('parsers', 'ParserController')
    ->only('index', 'store', 'show');

Route::group(['prefix' => 'mailings', 'as' => 'mailings.'], function () {
    Route::post('/preview', 'MailingController@preview')->name('preview');
    Route::get('/{mailing}/prepare', 'MailingController@prepare')->name('prepare');
    Route::post('/{mailing}/send', 'MailingController@send')->name('send');
});
Route::resource('mailings', 'MailingController');

Route::get('helper/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('helpers.logs');
Route::post('helper/combine', 'HelperController@combine')->name('helpers.combine');
Route::post('helper/word', 'HelperController@fromWord')->name('helpers.fromWord');
Route::get('helper', 'HelperController@index')->name('helpers.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'CategoryController@index')->name('catalog');
Route::get('category/{category}', 'CategoryController@show')->name('catalog.show');
Route::get('product/{product}', 'ProductController@show')->name('products.show');
Route::get('search', 'ProductController@search')->name('products.search');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/', 'HomeController@dashboard')->name('dashboard');
        Route::get('notifications', 'HomeController@notifications')->name('notifications.index');
        Route::get('orders', 'OrderController@index')->name('orders.index');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
    });
});


Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', 'CartController@index')->name('index');
    Route::post('add-to-cart', 'CartController@addToCart')->name('add-to-cart');
    Route::get('add/{offer}', 'CartController@add')->name('add');
    Route::get('remove/{offer}', 'CartController@remove')->name('remove');
    Route::get('delete/{offer}', 'CartController@removeAll')->name('delete');
    Route::get('clear', 'CartController@clearCart')->name('clear');
    Route::post('order', 'CartController@saveOrder')->name('order');
});

Route::any('test', 'HomeController@test');

Route::redirect('home', '/')->name('home');
Route::view('about', 'pages.about')->name('about');
Route::view('rules', 'pages.rules')->name('rules');
Route::view('contacts', 'pages.contacts')->name('contacts');
Route::view('feedback', 'pages.feedback')->name('feedback');

Route::get('catalog/{path?}', function($path = '/') {
    return redirect($path);
})->where('path', '.*');;

Route::get('{page}', 'PageController@show')->name('pages.show');

resources/views/admin/partials/admin-menu.blade.php
<nav class="nav small">
    <div class="container d-flex flex-wrap">
        <span class="nav-link">Админка:</span>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="productsManage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Товары
            </a>
            <div class="dropdown-menu" aria-labelledby="productsManage">
                <a class="dropdown-item" href="{{ route('admin.products.index') }}">Товары</a>
                <a class="dropdown-item" href="{{ route('admin.categories.index') }}">Категории</a>
                <a class="dropdown-item" href="{{ route('admin.suppliers.index') }}">Поставщики</a>
                <a class="dropdown-item" href="{{ route('admin.images.index') }}">Изображения</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('admin.import.index') }}">Импорт товаров</a>
                <a class="dropdown-item" href="{{ route('admin.parsers.index') }}">Парсинг товаров</a>
                <a class="dropdown-item" href="{{ route('admin.helpers.index') }}">Помощники</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="cartsManage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Заказы
            </a>
            <div class="dropdown-menu" aria-labelledby="cartsManage">
                <a class="dropdown-item" href="{{ route('admin.orders.index') }}">Последние заказы</a>
                <a class="dropdown-item" href="{{ route('admin.carts.index') }}">Незавершенные заказы</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="productsManage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Пользователи
            </a>
            <div class="dropdown-menu" aria-labelledby="productsManage">
                <a class="dropdown-item" href="{{ route('admin.users.index') }}">Зарегистрированные пользователи</a>
                <a class="dropdown-item" href="{{ route('admin.users.invites.index') }}">Приглашенные пользователи</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('admin.roles.index') }}">Группы пользователей</a>
            </div>
        </li>
        <li class="nav-item"><a class="nav-link" href="{{ route('admin.mailings.index') }}">Рассылки</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ route('admin.pages.index') }}">Страницы</a></li>

    </div>
</nav>

resources/views/admin/partials/alert-status.blade.php
@if (session('status'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @if (is_array(session('status')))
            @foreach (session('status') as $status)
                {{ $status }}
            @endforeach
        @else
            {{ session('status') }}
        @endif
    </div>
@endif

@if (isset($errors) && $errors->any())
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ $error }}
        </div>
    @endforeach
@endif